#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""从 class/index.html 模板 + info_data.py 文案，生成《眼见为虚》books/info/index.html。
一次性脚本：读模板 style/script 原样保留，仅替换 title/封面/内容页/页数。"""

import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from info_data import PAGES

TPL = os.path.join(ROOT, "books/class/index.html")
OUT = os.path.join(ROOT, "books/info/index.html")

CN_NUM = ["壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾", "拾壹", "拾贰"]

with open(TPL, encoding="utf-8") as f:
    tpl = f.read()

# 1) head（到 <body> 前），替换 <title>
head = tpl.split("<body>")[0]
head = head.replace("<title>阶级的秘密 · 点点的书架</title>",
                    "<title>眼见为虚 · 点点的书架</title>")

# 2) 页面尾部 <script>（翻页/双击/键盘/触摸逻辑，位于 </style> 之后第二个 <script>），替换 totalPages
marker = '<div class="dots" id="dots"></div>'
script = tpl[tpl.index(marker) + len(marker):]
script = script.replace("const totalPages = 18;", "const totalPages = 13;")

# 3) 封面
cover = """  <!-- Page 0: Cover -->
  <div class="page cover active" data-page="0">
    <div class="cover-bg">
      <img src="images/01_cover.png" alt="眼见为虚">
    </div>
    <div class="page-content">
      <div class="cover-title">眼见为虚</div>
      <div class="cover-subtitle">你看到的，是谁想让你看到的</div>
      <div class="cover-meta">讲给点点的 13 个故事</div>
    </div>
  </div>
"""

# 4) 内容页
pages_html = []
for i, (num, slug, title, subtitle, paras, takeaway, img_prompt, model_name, model_alt) in enumerate(PAGES[1:]):
    img = f"images/{num}_{slug}.png"
    glb = f"../../assets/models/{model_name}.glb"
    paras_html = "\n        ".join(f"<p>{p}</p>" for p in paras)
    page = f"""
  <!-- Page {i+1}: {title} -->
  <div class="page" data-page="{i+1}">
    <div class="page-content">
      <div class="page-title">{title}</div>
      <div class="page-subtitle">{subtitle}</div>
      <div class="page-body">
        {paras_html}
        <div class="key-takeaway">
          <strong>信息的逻辑：</strong>{takeaway}
        </div>
      </div>
      <div class="page-num">{CN_NUM[i]}</div>
    </div>
    <div class="page-media">
      <div class="media-item" ondblclick="openModal('{img}', 'image')">
        <img src="{img}" alt="{title}">
        <div class="media-label">双击放大</div>
      </div>
      <div class="media-divider"></div>
      <div class="media-item" ondblclick="openModal('{glb}', 'model')">
        <model-viewer src="{glb}" alt="{model_alt}" auto-rotate camera-controls shadow-intensity="1" exposure="0.8" style="--poster-color: transparent;"></model-viewer>
        <div class="media-label">3D模型 · 双击全屏</div>
      </div>
    </div>
  </div>
"""
    pages_html.append(page)

# 5) 导航 + modal + dots（与模板一致）
tail = """
</div>

<!-- Navigation -->
<div class="nav">
  <button id="prevBtn" onclick="changePage(-1)">‹</button>
  <span class="page-indicator" id="indicator">1 / 13</span>
  <button id="nextBtn" onclick="changePage(1)">›</button>
</div>

<!-- Fullscreen Modal -->
<div class="modal" id="modal">
  <button class="modal-close" onclick="closeModal()">×</button>
  <div class="modal-content" id="modalContent"></div>
  <div class="modal-hint">拖拽旋转 · 滚轮缩放 · 点击 × 关闭</div>
</div>

<!-- Progress dots -->
<div class="dots" id="dots"></div>

"""

html = (head
        + "<body>\n\n"
        + '<a class="home-link" href="../../index.html">‹ 返回书架</a>\n\n'
        + '<div id="book">\n\n'
        + cover
        + "".join(pages_html)
        + tail
        + script)

with open(OUT, "w", encoding="utf-8") as f:
    f.write(html)

# 校验
n_pages = html.count('class="page"') + html.count('class="page cover active"')
print(f"written: {OUT}")
print(f"content pages (data-page>=1): {len(pages_html)}")
print(f"totalPages in script: {'const totalPages = 13;' in html}")
print(f"dots generated by JS loop over totalPages => 13")
print(f"title ok: {'眼见为虚 · 点点的书架' in html}")
