# -*- coding: utf-8 -*-
"""《眼见为虚》13 页文案。结构同 class_data.py。"""

STYLE = "Fresh detailed digital painting, ink indigo and warm amber with crimson accents color palette, cinematic light, slightly dreamlike modern children's book illustration, historically evocative, no text."

PAGES = [
 ("01","cover","封面","","","","","",""),

 ("02","beacon","公元前8世纪，烽火戏诸侯","最早的'假消息'，亡了一个国",
  ["西周的周幽王，为了逗宠妃褒姒笑，干了一件蠢事。",
   "他点燃了<span class='highlight'>烽火</span>——那是边疆告急、喊诸侯带兵来救的信号，轻易不能点。",
   "诸侯们火急火燎赶来，却发现根本没有敌人，只是博美人一笑。褒姒果然笑了，诸侯们的脸却黑了。",
   "后来敌人真的来了，周幽王再点烽火——<span class='highlight'>没有一个人来救他。</span>西周就这么亡了。<span class='highlight'>假消息最毒的代价，是让真的也没人信了。</span>"],
  "最早的信息事故：烽火是假的，亡的是国。撒谎的代价，是让真话也没人信。",
  "Ancient China Western Zhou: a king lighting beacon fires on the Great Wall watchtowers at night to amuse his concubine, feudal lords rushing with armies only to find no enemy, the fatal false alarm, dramatic firelight and dark mountains.",
  "beacon_fire","烽火台"),

 ("03","monk","中世纪的抄经院","知识被锁起来的年代",
  ["在印刷术发明前，欧洲的书全靠人<span class='highlight'>用手一个字一个字抄</span>。",
   "一本书要抄好几个月，贵得吓人，只有教会和贵族买得起。",
   "谁掌握了抄书的权力，谁就掌握了'什么是知识'。普通人看不到书，<span class='highlight'>只能听教士说书里有</span>什么——他说什么，你就得信什么。",
   "这是一种很隐蔽的权力：<span class='highlight'>控制了信息的入口，就控制了人的脑子。</span>"],
  "信息被垄断的年代：谁控制抄书，谁就控制知识。垄断信息入口，就是垄断思想。",
  "A medieval monastery scriptorium: monks hand-copying manuscripts by candlelight, precious chained books, common people outside unable to read, knowledge locked away, candlelight and shadow, amber and indigo.",
  "manuscript","手抄经卷"),

 ("04","gutenberg","1440年，古登堡的印刷机","一台机器，炸开信息的墙",
  ["1440年前后，德国人古登堡造出了<span class='highlight'>活字印刷机</span>。",
   "以前抄一本书要几个月，现在一天能印几百本。书一下子便宜了，普通人也买得起了。",
   "结果怎样？知识像决堤的水一样涌出来。马丁·路德写的批评教会的小册子，<span class='highlight'>两个星期传遍德国</span>——这在抄书时代想都不敢想。",
   "教会对信息的垄断，被一台机器砸得粉碎。<span class='highlight'>每当信息变便宜，垄断者的墙就会塌。</span>这在《阶级的秘密》里我们也讲过。"],
  "印刷机让信息变便宜，砸碎了垄断。技术每降低一次信息的成本，就解放一次思想。",
  "Gutenberg's printing press: movable type letters, fresh printed pages flying off the press, knowledge escaping as light from a dark monastery into the hands of ordinary townsfolk, revolutionary energy, amber breakthrough.",
  "printing_press","印刷机"),

 ("05","yellow","1890年代，'黄色新闻'","标题党，一百年前就有了",
  ["别以为标题党是网络时代的产物，一百多年前的美国报纸就玩得很溜了。",
   "当时两家大报纸为了抢读者，比赛谁的标题<span class='highlight'>更夸张、更煽情、更吓人</span>。因为报上常印一个穿黄衣服的漫画小孩，被人叫'黄色新闻'。",
   "它们甚至拼命渲染'西班牙威胁'，煽风点火，硬是<span class='highlight'>把美国舆论推向了战争</span>。",
   "看出来了吗？<span class='highlight'>为了'点击量'（那时候叫销量），媒体可以牺牲真相。</span>这个毛病，到今天一点没改。"],
  "黄色新闻=一百年前的标题党：为了销量牺牲真相，甚至能煽动战争。流量至上古已有之。",
  "1890s New York: rival newspaper boys shouting exaggerated sensational headlines, bold scary front pages, a yellow kid cartoon character, newspapers whipping public opinion toward war, frenzied media circus, ink and amber.",
  "newspaper","黄色新闻报"),

 ("06","radio","1930年代，无线电与宣传","声音，第一次能灌进千万人的耳朵",
  ["无线电发明后，信息第一次可以<span class='highlight'>同时送进千家万户</span>。",
   "这本来是好事。可1930年代的德国，纳粹把它用到了极致：让收音机变得极便宜，家家都有，然后<span class='highlight'>天天在广播里灌输仇恨和谎言</span>。",
   "同一个声音，重复一千遍，很多人就把它当成了真理。",
   "这是一个可怕的发现：<span class='highlight'>谎言重复得够多、传得够广，就能伪装成真相。</span>渠道越强大，被滥用的后果越可怕。"],
  "无线电让声音能同时洗脑千万人。谎言重复千遍即成'真理'——渠道越强，越要警惕。",
  "1930s Germany: a cheap radio in every home broadcasting a single hypnotic voice, waves of repeated messages flowing over a city, families listening intently, the power and danger of mass propaganda, ominous amber-indigo mood.",
  "radio","收音机"),

 ("07","tv","1950年代，电视时代","画面，比真相更有力",
  ["电视来了，信息从'听的'变成'看的'。这又一次改变了权力的游戏。",
   "1960年，美国第一次电视直播总统辩论。收音机前的听众觉得尼克松赢了；可看电视的人，看到的是<span class='highlight'>肯尼迪更精神、更上镜</span>，于是认定肯尼迪赢。",
   "内容差不多，<span class='highlight'>赢的却是'看起来更好'的那个</span>。",
   "电视教会政客一件事：<span class='highlight'>形象比观点重要，画面比真相有力。</span>从此，'看起来怎样'越来越压倒'实际是怎样'。"],
  "电视时代：形象压倒观点，画面压倒真相。'看起来如何'开始比'实际如何'更重要。",
  "1960 US presidential debate on TV: a split between radio listeners and TV viewers, a vigorous telegenic Kennedy versus a sweating Nixon on the glowing screen, image triumphing over substance, black-and-white TV glow with amber room.",
  "television","电视机"),

 ("08","internet","2000年代，人人自媒体","每个人都能发声，然后呢",
  ["互联网来了，彻底变了天：以前只有报社、电视台能发声，<span class='highlight'>现在人人拿起手机就能发</span>。",
   "这当然是巨大的解放——垄断被打破了，普通人也有了话筒。",
   "可新问题跟着来了：<span class='highlight'>谁都能说，那谁说的是真的？</span>信息从'太少'变成了'太多'，真的假的混在一起，淹得你喘不过气。",
   "过去的问题是'看不到'，现在的问题是'<span class='highlight'>看不过来、分不清</span>'。信息时代，稀缺的不再是信息，而是<span class='highlight'>分辨真假的能力</span>。"],
  "互联网打破垄断，人人可发声。但信息从太少变太多，稀缺的变成'分辨真假的能力'。",
  "The internet age: millions of people each holding up their own glowing phone as a microphone, a chaotic flood of information, truth and lies mixed together as light and dark streams, overwhelming abundance, indigo and amber chaos.",
  "smartphone","智能手机"),

 ("09","algorithm","2010年代，算法推荐","你爱看什么，它就喂你什么",
  ["信息太多了，看不完，于是平台派出了'算法'帮你挑。",
   "它像个特别懂你的服务员：你多看两眼猫，它就推一堆猫；你点开一个球星，它就塞满球星。<span class='highlight'>你越爱看什么，它越喂你什么。</span>",
   "听起来贴心，对吧？但你想过没有——<span class='highlight'>它关心的不是'你该知道什么'，而是'什么能让你一直看下去'</span>，因为你看得越久，它越赚钱。",
   "于是，你爱看的越推越多，<span class='highlight'>你不一样、但也许更重要的东西，悄悄从眼前消失了</span>。"],
  "算法只在乎让你'一直看'，不在乎让你'看得全'。它喂你爱看的，藏起你需要的。",
  "A glowing algorithmic server feeding personalized streams into a person's phone: whatever they glance at multiplies, a recommendation engine like an attentive but self-serving waiter, longer watch time flowing to the platform as coins, indigo tech with amber lure.",
  "algorithm","算法"),

 ("10","bubble","过滤气泡","世界，只剩你想看的那一块",
  ["算法天天喂你爱看的，时间一长，会发生什么？",
   "你会像住进一个<span class='highlight'>透明的气泡</span>里：气泡里全是你认同的观点、喜欢的东西，舒舒服服。",
   "可气泡外的世界——不一样的想法、你没见过的风景、能纠正你的真话——<span class='highlight'>你全都看不见了</span>。",
   "更麻烦的是，气泡里的人容易觉得'<span class='highlight'>全世界都和我想的一样</span>'，遇到不同意见就觉得对方不可理喻。大家越来越吵、越来越对立。还记得吗？这正是《环境的秘密》里讲过的环境的力量。"],
  "过滤气泡：算法把你裹进舒适的信息茧房，让你以为全世界都和你想的一样。",
  "A person walking inside a transparent bubble made of curved screens all showing the same agreeable content, comfortable inside, while a vast colorful diverse world of different ideas lies unseen outside the bubble, indigo bubble with amber outside world.",
  "filter_bubble","过滤气泡"),

 ("11","fake","假新闻为什么比真相跑得快","越刺激，传得越远",
  ["有人研究过：在社交媒体上，<span class='highlight'>假消息比真消息传得更快、更远、更广</span>。",
   "为什么？因为真相常常是平淡的，而假消息可以<span class='highlight'>随便编，怎么刺激怎么来</span>：更吓人、更解气、更离奇、更符合你想听的。",
   "人天生就爱传播刺激的事。假消息正好掐住了这个弱点，像病毒一样疯传。",
   "所以记住一个规律：<span class='highlight'>一条消息越是让你特别激动、特别想立刻转发，越要先打个问号。</span>情绪，是假消息最好的燃料。"],
  "假新闻比真相跑得快，因为它更刺激、更挠到情绪。越让你激动想转发的，越要先怀疑。",
  "A race between truth and fake news: a slow plain tortoise of truth versus a flashy rocket of fake news spreading like wildfire through networks of people, emotion as fuel, sensational viral spread, crimson warning with indigo network.",
  "fake_news","假新闻"),

 ("12","deepfake","2024年，AI 与深伪","连眼睛，也不能全信了",
  ["以前我们说'耳听为虚，眼见为实'。可到了AI时代，这句话不灵了。",
   "现在的AI，能做出<span class='highlight'>以假乱真的假照片、假视频、假声音</span>：能让一个名人'说'他从没说过的话，让一个人'出现'在他从没去过的地方，连你妈妈的声音都能模仿。",
   "这叫'深度伪造'。以后你看到一段视频，哪怕画面清清楚楚，<span class='highlight'>也得问一句：这是真的吗？</span>",
   "连眼睛都不能全信的时代，什么最可靠？<span class='highlight'>是你脑子的判断，和多方求证的耐心。</span>这是2024年以后，每个人都必须练的本事。"],
  "AI深伪时代，眼见不再为实。最后可靠的，是你的判断力和多方求证的习惯。",
  "Year 2024: an AI generating a hyper-realistic fake video and cloned voice of a person, pixels rearranging into a convincing but false face, eyes that can no longer be trusted, a magnifying glass of scrutiny over media, teal AI with crimson caution.",
  "deepfake","深度伪造"),

 ("13","dot","写给点点：多问一句'真的吗'","你的眼睛，你做主",
  ["点点，从烽火台讲到AI深伪，这本书其实只讲了一件事：<span class='highlight'>你看到的，未必是全部的真相，也未必是真的。</span>",
   "几千年来，总有人想控制你看到什么——为的是控制你怎么想。从抄经的教士，到煽情的报纸，到今天的算法和AI。",
   "那怎么办？给你三个小办法：",
   "<span class='highlight'>一、看到特别激动的消息，先停三秒，问一句'真的吗'。</span>",
   "<span class='highlight'>二、别只在一个地方看，多找几个来源对对。</span>三、分清'事实'和'观点'：'今天下雨'是事实，'下雨真讨厌'是观点。",
   "愿你在信息的汪洋里，<span class='highlight'>不当随波逐流的浮萍，做一个有锚的人。眼见为虚，脑证为实。</span>"],
  "全书落点：眼见为虚，脑证为实。面对信息，多问'真的吗'、多方求证、分清事实与观点。",
  "A thoughtful child standing firmly like a lighthouse keeper amid a stormy sea of swirling information, holding a steady lamp of judgment and an anchor, behind a spiral of media history: beacon fire, manuscript, printing press, newspaper, radio, TV, smartphone, AI, all dissolving into stars, calm amber light.",
  "lighthouse","灯塔"),
]
