# -*- coding: utf-8 -*-
"""《钱是什么》13 页文案。结构同 class_data.py。
(num, file, title, subtitle, [正文...], takeaway, 图片prompt, 模型名, 模型alt)
"""

STYLE = "Fresh detailed digital painting, warm gold and copper with deep teal accents color palette, cinematic light, slightly dreamlike modern children's book illustration, historically evocative, no text."

PAGES = [
 ("01","cover","封面","","","","","",""),

 ("02","barter","公元前9000年，用羊换斧头的麻烦","没有钱的年代，交换有多难",
  ["很久以前，世界上没有钱。你想要别人的东西，只能拿自己的东西去换。",
   "你家养羊，想吃麦子，就得牵一只羊去找种麦子的人。可问题来了——",
   "万一人家<span class='highlight'>不要羊，只要盐</span>呢？你得先把羊换成盐，再拿盐去换麦子。绕一大圈，腿都跑断了。",
   "而且，一只羊怎么分？半只羊就死了。交换实在太麻烦了。<span class='highlight'>人们急需一个'大家都认的中间物'。</span>"],
  "钱的起点：交换太麻烦，人们需要一个大家都愿意接受的中间物。这就是钱的雏形。",
  "An ancient barter market scene: a herder awkwardly trying to trade a live sheep for sacks of grain, the grain seller shaking his head pointing at salt instead, a chaotic web of exchange with many frustrated people, warm earthy tones.",
  "sheep","羊"),

 ("03","shell","贝壳、盐和石头","什么东西能当钱",
  ["慢慢人们发现，有些东西特别适合当'中间物'。",
   "海边的人用<span class='highlight'>贝壳</span>——漂亮、稀少、好携带、坏不了；有的地方用<span class='highlight'>盐</span>——人人都要吃盐；太平洋有个岛，居然用大石头当钱。",
   "看出规律了吗？能当钱的东西，必须<span class='highlight'>稀少、耐用、好带、大家都认</span>。",
   "在中国，'钱'这个字，偏旁是'贝'。因为最早的汉字里，<span class='highlight'>钱就是贝壳变的</span>。"],
  "能当钱的东西有四个条件：稀少、耐用、好携带、大家都认。贝壳、盐、石头都当过钱。",
  "A display of ancient money forms across cultures: beautiful cowrie shells, blocks of white salt, and a giant round stone coin, arranged like museum treasures with soft light, diverse ancient peoples trading with them.",
  "cowrie","贝壳"),

 ("04","coin","公元前600年，第一枚金币","国家盖章，信任诞生",
  ["贝壳虽好，可大小不一、容易碎。人们想要更标准的钱。",
   "在小亚细亚有个叫吕底亚的王国（今天的土耳其），他们做了一件大事：",
   "把金银铸成<span class='highlight'>大小、重量都一样的圆片</span>，还在上面<span class='highlight'>盖上国王的印章</span>。",
   "这个章的意思是：<span class='highlight'>'我保证它值这么多。'</span>从此，你不用称重量、不用验成色——看到章就放心。<span class='highlight'>钱，第一次有了'国家信用'。</span>"],
  "硬币的关键不是金属，是上面那个章——国家替它担保。钱开始有了信用。",
  "The kingdom of Lydia: a craftsman striking the first gold coin with a lion seal stamp, gleaming electrum coins in a pile, a king's authority behind standardization, ancient Anatolian golden light.",
  "gold_coin","金币"),

 ("05","jiaozi","公元1000年，北宋的交子","中国人最早把纸变成钱",
  ["铜钱、金币太重了。买一匹好马，得拉一车子钱，又沉又招贼。",
   "北宋时，四川的商人想了个办法：把钱存在铺子里，铺子开一张<span class='highlight'>纸做的凭证</span>，叫<span class='highlight'>'交子'</span>。",
   "你拿着这张纸，到别处就能换钱、买东西。纸比铜钱轻多了，生意一下子好做了。",
   "这是<span class='highlight'>全世界最早的纸币</span>，比欧洲早了好几百年。一张纸能当钱，靠的是<span class='highlight'>大家相信它能换回真钱</span>。"],
  "交子是世界最早的纸币。纸本身不值钱，值钱的是背后的'相信'。",
  "Northern Song dynasty China: a merchant handing a printed paper jiaozi note across a counter in a Sichuan money shop, strings of heavy copper coins behind, elegant Chinese woodblock print patterns on the paper, Song era prosperity.",
  "jiaozi","交子"),

 ("06","bank","1400年，威尼斯的银行家","坐在长凳上，凭空造钱",
  ["意大利威尼斯，商人们来来往往，带着各国的钱，兑换特别麻烦。",
   "于是出现了一种人，坐在广场的长凳上，帮你<span class='highlight'>换钱、存钱、记账</span>。'银行'这个词，就是从意大利语'长凳'来的。",
   "后来他们发现：存钱的人不会同时来取钱。于是<span class='highlight'>把别人存的钱，偷偷借出去收利息</span>——手里的钱，就这么'变多'了。",
   "这就是银行的秘密：<span class='highlight'>你存一块钱，银行能把它当成好几块钱用。</span>钱，开始被'造'出来。"],
  "银行靠'借短放长'造钱：你存的钱，银行转手借给别人，钱就这样被放大了。",
  "Renaissance Venice: a banker at a wooden bench (banco) on a bustling square, ledgers and scales and bags of coins, merchants from many lands exchanging currencies, ships in the canal behind, golden Mediterranean light.",
  "bank_bench","银行长凳"),

 ("07","gold_std","1800年代，金本位的承诺","一张纸背后的黄金",
  ["纸币方便，可总有人不放心：万一这纸变不出钱呢？",
   "各国想了个让人安心的办法，叫<span class='highlight'>金本位</span>：政府承诺，<span class='highlight'>你手里的每一张纸币，随时能到银行换回固定重量的黄金</span>。",
   "这下没人慌了。纸币背后有真金兜底，大家用得踏踏实实。",
   "你看，钱越来越'虚'，但靠的是一句越来越实的<span class='highlight'>承诺</span>。问题是——这个承诺，能一直兑现吗？"],
  "金本位：纸币能随时换黄金。钱的信用，靠'能兑现'这三个字撑着。",
  "A 19th century bank: a citizen handing paper banknotes through a window and receiving gleaming gold bars in return, a large vault of stacked gold behind the teller, an engraved promise on the banknote, Victorian era trust and solidity.",
  "gold_bar","金条"),

 ("08","1971","1971年，美元和黄金分手","从那天起，钱只剩'信'",
  ["1971年，发生了一件改变全世界的事。",
   "美国总统尼克松宣布：<span class='highlight'>美元不再兑换黄金</span>。那句'随时换真金'的承诺，作废了。",
   "从那天起，钱背后不再有金子了。那一美元、一百块，<span class='highlight'>只是一张纸、一个数字</span>。",
   "那它为什么还能买东西？因为<span class='highlight'>所有人都相信它有用</span>，国家也用法律给它撑腰。钱，彻底变成了一种<span class='highlight'>'信心'</span>。只要信心在，纸就是钱。"],
  "1971年后，钱和黄金脱钩。今天的钱不靠金子，靠的是'所有人的相信'加'国家信用'。",
  "1971: a symbolic scene of a US dollar bill being snipped away from a gold bar with scissors, the two separating, on one side solid gold, on the other side a paper note floating on pure confidence and trust, dramatic split lighting.",
  "cut_dollar","美元与黄金分离"),

 ("09","inflation","中央银行，钱的总闸门","钱为什么会'变毛'",
  ["每个国家都有一个管钱的'总闸门'，叫<span class='highlight'>中央银行</span>（中国的叫中国人民银行，美国的叫美联储）。",
   "它能决定：<span class='highlight'>印多少钱、钱借出去贵不贵</span>。",
   "如果印太多钱，东西还是那么多，那每块钱能买到的东西就变少了——以前一块钱一根冰棍，后来要五块。这叫<span class='highlight'>通货膨胀</span>，老人管它叫'钱变毛了'。",
   "所以央行的工作，是<span class='highlight'>让钱不多不少刚刚好</span>：太少经济转不动，太多钱就毛了。这是个技术活。"],
  "央行是钱的总闸门。钱印多了会通货膨胀——同样的钱，买到的东西变少了。",
  "A grand central bank as a giant valve or faucet controlling the flow of golden coins into an economy, too much flow causing prices (a popsicle, bread) to float up like balloons, a careful hand on the valve, symbolic and clear.",
  "money_faucet","货币水龙头"),

 ("10","digital","2010年代，手机里的数字钱","钱变成了看不见的信号",
  ["到了点点这一代，钱又变了——连纸都看不见了。",
   "爸爸妈妈买早点，掏出手机'嘀'一下；你过生日，爷爷奶奶发来个红包。钱变成了<span class='highlight'>手机里的一串数字</span>。",
   "这背后，是微信、支付宝在帮你<span class='highlight'>记账</span>：你扫一下，它就从你的账户减一点，给商家的账户加一点。",
   "方便是真方便，但也意味着：<span class='highlight'>你的每一笔钱，平台都记得清清楚楚。</span>钱越方便，越离不开那套记账的系统。"],
  "移动支付让钱变成数字信号。方便的背后，是平台在替你记账——它记得你的每一分钱。",
  "Modern China: a hand holding a smartphone scanning a QR code at a small breakfast stall, digital coins flowing as light from the phone to the vendor's phone, an elderly person sending a red envelope digitally, warm street morning light.",
  "qr_payment","扫码支付"),

 ("11","credit","信用卡与花呗：花明天的钱","先享受，后付钱，谁赚了",
  ["还有一种钱，更神奇——<span class='highlight'>你还没挣到，就能先花</span>。",
   "信用卡、花呗，都是这个逻辑：先看中的东西先买，<span class='highlight'>下个月再还钱</span>。",
   "听起来很美，对吧？但如果你还不上，或者只还一点点，剩下的就要付<span class='highlight'>利息</span>——而且利息不低。",
   "这就是它赚钱的方式：<span class='highlight'>它巴不得你慢慢还，还得越慢，它赚得越多。</span>先甜后苦，世界上最贵的东西，常常是'免费先用'的。"],
  "信用卡和花呗让你'花明天的钱'。方便的另一面是利息——它最希望你慢慢还。",
  "A shiny credit card and a smartphone with a buy-now-pay-later app, a person happily taking home purchases today, but a long shadow of growing interest charges following behind like a tail, sweet-then-bitter visual metaphor.",
  "credit_card","信用卡"),

 ("12","bitcoin","2009年，比特币","代码能当钱吗",
  ["既然钱靠的是'相信'，那能不能<span class='highlight'>不靠国家、不靠银行</span>，造一种钱？",
   "2009年，一个自称'中本聪'的神秘人（到现在也没人知道他是谁），做出了<span class='highlight'>比特币</span>。",
   "它没有银行管，靠的是一套全世界电脑一起维护的账本，谁也改不了、赖不掉。总量还写死在代码里，只有2100万个，谁都印不出来。",
   "有人说这是未来，有人说这是泡沫。但它证明了一件事：<span class='highlight'>人们开始尝试，用代码来建立'信任'，而不是用银行和政府。</span>"],
  "比特币是场实验：不要银行，用代码和算法来建立信任。它还在路上，但想法很大胆。",
  "A glowing bitcoin symbol emerging from a network of connected computers worldwide, lines of code forming a decentralized ledger, no central bank, mysterious figure of Satoshi fading into digital mist, futuristic blue-gold light.",
  "bitcoin","比特币"),

 ("13","dot","写给点点：钱不是目的","看懂钱，才不会被钱牵着走",
  ["点点，从一只羊讲到比特币，其实就一句话：<span class='highlight'>钱是人们'约定好都相信'的东西。</span>",
   "贝壳也好、金币也好、手机里的数字也好，它们本身都不值钱。值钱的，是<span class='highlight'>背后那份信任</span>。",
   "所以记住两件事：第一，钱会变。今天的纸币，也许几十年后就像贝壳一样进了博物馆。",
   "第二，也是最重要的——<span class='highlight'>钱是工具，不是目的</span>。有人拼命追钱，最后成了钱的奴隶；有人看懂钱，让钱帮自己做事、帮别人解难。",
   "愿你是后者：<span class='highlight'>看懂钱，用好钱，但永远不要只为了钱。</span>"],
  "全书落点：钱是信任的工具，不是人生的目的。看懂它，是为了驾驭它，而不是被它驾驭。",
  "A hopeful child at a window at dawn, holding a piggy bank from which a spiral of money history rises: a sheep, shells, a gold coin, a paper note, a gold bar, a smartphone, a bitcoin, all dissolving into warm stars, the child smiling wisely, golden light.",
  "piggy_bank","存钱罐"),
]
