# -*- coding: utf-8 -*-
"""《谁说了算》13 页文案。结构同 class_data.py。"""

STYLE = "Fresh detailed digital painting, deep bronze and slate blue with warm gold accents color palette, cinematic light, slightly dreamlike modern children's book illustration, historically evocative, no text."

PAGES = [
 ("01","cover","封面","","","","","",""),

 ("02","strong","远古部落，最强壮的人说了算","权力的第一种来源：拳头",
  ["远古时代，一个部落谁说了算？多半是<span class='highlight'>最强壮、最会打猎的那个人</span>。",
   "这很合理：猛兽来了他顶上去，食物不够他带队去找。大家服他，是因为他能保护大家。",
   "这就是权力最原始的样子——<span class='highlight'>谁有能力带大家活下去，谁就说了算</span>。",
   "可是，拳头有个大问题：它会老，会输。等他打不过更年轻的人，权力就得换人。靠拳头，权力永远坐不稳。"],
  "权力最早靠能力（拳头）。但拳头会老，靠武力的权力坐不稳。",
  "A prehistoric tribe: the strongest hunter standing tall with a spear as the tribe gathers around him for protection, a saber-tooth threat in the shadows, firelight, primal respect but also younger rivals watching, raw and elemental.",
  "spear","长矛"),

 ("03","bloodline","拳头让位给血统","世袭：爸爸的位置传给儿子",
  ["后来，首领们想了个办法，让权力不用每次都重新打一架。",
   "办法很简单：<span class='highlight'>我死后，位置传给我儿子，儿子再传给孙子。</span>这叫'世袭'。",
   "从此，谁说了算，不再看谁最能干，而是看<span class='highlight'>谁是谁的儿子</span>。",
   "好处是稳定，不用打了。坏处也明显：<span class='highlight'>万一接班的孩子没本事呢？</span>血统，把'能者居之'变成了'生得好就赢'。"],
  "世袭让权力稳定传递，但也让'出身'取代了'能力'。生得好，比干得好更重要了。",
  "An ancient throne room: a dying old king placing a crown on a young boy's head, the crown passing by blood not by merit, courtiers bowing, a contrast between the capable old hand and the uncertain child, dynastic gold.",
  "crown","王冠"),

 ("04","god","公元前2000年，君权神授","给权力编一个故事",
  ["光靠血统，还是有人会不服：'凭什么你家世代当王？'",
   "于是统治者讲了一个更厉害的故事：<span class='highlight'>'我的权力，是神给的。'</span>",
   "埃及法老说自己是太阳神的儿子，中国的皇帝自称'天子'——上天的儿子。你要反他，就是反天、反神。",
   "这个故事太管用了。<span class='highlight'>只要大家信了，没人敢反抗。</span>权力第一次发现：比起拳头，<span class='highlight'>一个好故事，才是最省力的统治工具</span>。"],
  "君权神授：权力靠'故事'来合理化。让被统治者相信，是最省力的统治。",
  "An Egyptian pharaoh crowned by rays from the sun god, and a Chinese emperor receiving the Mandate of Heaven, split scene, divine light descending on both rulers, awed people kneeling, the power of a sacred story, mystical golden-teal light.",
  "sun_crown","神授王冠"),

 ("05","qin","公元前221年，秦始皇","一个人说了算的帝国",
  ["在中国，秦始皇干了一件前所未有的事：把七个国家打成一个，<span class='highlight'>全天下的权力，攥在他一个人手里</span>。",
   "他统一文字、统一度量衡、修长城、修驰道。一个人拍板，全国照办，效率高得惊人。",
   "可问题是：<span class='highlight'>权力太集中，对错全看一个人。</span>他英明，天下受益；他犯浑，全国遭殃。",
   "果然，他死后没几年，大秦就垮了。<span class='highlight'>一个人说了算，快是快，可一旦错了，没人拉得住。</span>"],
  "高度集权效率极高，但对错全系于一人。一个人说了算，最怕那个人犯错。",
  "Qin dynasty: Emperor Qin Shi Huang alone at the center of a vast empire map, standardizing script and measures, the Great Wall and straight roads radiating from his single commanding figure, immense centralized power, imposing bronze tones.",
  "empire_map","帝国版图"),

 ("06","rome","公元前500年，罗马元老院","一群老人，互相牵制",
  ["差不多同一时期，罗马人走了另一条路。他们赶走了国王，说：<span class='highlight'>权力不能给一个人。</span>",
   "他们设了个'元老院'，由一群有经验的贵族老人<span class='highlight'>商量着来</span>，还设了两个'执政官'，互相牵制，谁也不能独断。",
   "一个人犯错，还有人纠正。这让罗马强大了好几百年。",
   "你看，这是和秦始皇完全相反的思路：<span class='highlight'>与其赌一个人永远英明，不如让权力互相盯着。</span>"],
  "罗马用分权代替集权：多人协商、互相牵制，避免把命运押在一个人身上。",
  "The Roman Senate: a semicircle of elderly toga-clad senators debating and voting, two consuls checking each other, no single throne, balanced shared power, marble and laurel, classical republican dignity.",
  "senate","元老院"),

 ("07","magna","1215年，大宪章","第一次给国王套上笼子",
  ["国王权力再大，就没人管得了他吗？英国的贵族们不服。",
   "1215年，他们逼着国王签下一份文件，叫<span class='highlight'>《大宪章》</span>。上面写着一句石破天惊的话：",
   "<span class='highlight'>国王，也要遵守法律。</span>不能想抓谁就抓谁，想收多少税就收多少税。",
   "这是人类历史上第一次，<span class='highlight'>把最高的权力，也关进了'规则'的笼子里</span>。从此有了个新观念：不是你官大你就对，而是<span class='highlight'>规则比人更大</span>。"],
  "大宪章的意义：连国王也要守法。权力第一次被'规则'约束，法治从此萌芽。",
  "England 1215: angry barons forcing a reluctant King John to seal the Magna Carta at Runnymede, a great charter document, the king's power being chained by written law, dramatic tension, medieval parchment and wax seal.",
  "charter","大宪章"),

 ("08","revolution","1789年，法国大革命","权力还给人民？",
  ["大宪章管住了国王一点，但老百姓还是没权。几百年后，法国人忍不了了。",
   "还记得我们在《阶级的秘密》里讲的吗？教士和贵族只占2%，却免税；98%的人养活他们。",
   "1789年，人民爆发了，喊出<span class='highlight'>'自由、平等、博爱'</span>，把国王送上了断头台。权力，第一次号称要还给'人民'。",
   "可接下来的故事有点乱：革命之后是恐怖、是混战、最后又来了个皇帝拿破仑。<span class='highlight'>推翻旧权力容易，建好新权力，难得多。</span>"],
  "大革命想还权于民，但推翻旧权力容易，建立稳定的新权力难得多。",
  "French Revolution 1789: crowds storming with the tricolor flag, the words liberty equality fraternity, the fall of a king, but also chaos and a guillotine's shadow and a rising Napoleon in the background, turbulent revolutionary energy.",
  "revolution","大革命"),

 ("09","vote","选票：人人都有了权","一人一票的力量与陷阱",
  ["折腾了很久，人类慢慢找到一种办法：<span class='highlight'>一人一票，投票选说了算的人。</span>",
   "这个办法好在哪？权力来自大家的同意，选得不好，下次还能换掉。和平、有序。",
   "但选票也有陷阱。有人靠<span class='highlight'>讲好听的话</span>骗票；有人许诺'<span class='highlight'>发福利</span>'拉票，其实是要拿你的钱买好；还有人多欺负人少。",
   "所以投票不是万能的。它只是让人类的权力游戏，<span class='highlight'>从'动刀动枪'，变成了'动嘴动票'</span>——这已经是巨大的进步。"],
  "选票让权力来自同意、可以和平更换。但要警惕：有人会用甜言蜜语和空头福利骗走你的票。",
  "A modern voting scene: diverse citizens casting paper ballots into a transparent box, one person one vote, but also a slick demagogue whispering promises on one side, the double edge of democracy, hopeful yet cautious light.",
  "ballot_box","投票箱"),

 ("10","threes","枪杆子、笔杆子、钱袋子","权力背后的三根柱子",
  ["说来说去，权力到底靠什么撑住？其实就三样东西。",
   "第一是<span class='highlight'>枪杆子</span>：武力和军队，你不服就压你。这是最硬的。",
   "第二是<span class='highlight'>笔杆子</span>：宣传和故事，让你从心里认同它。还记得'君权神授'吗？这是最巧的。",
   "第三是<span class='highlight'>钱袋子</span>：掌握钱的分配，让跟着你的人有好处。这是最实的。",
   "从古到今，不管叫什么名字的权力，扒开看，都离不开这三根柱子。<span class='highlight'>看懂了它们，你就看懂了权力的底牌。</span>"],
  "权力的三根支柱：武力（枪）、叙事（笔）、利益（钱）。看透这三样，就看透了权力。",
  "Three symbolic pillars holding up a seat of power: a rifle (military force), a quill pen (narrative and propaganda), and a money bag (wealth and distribution), a throne resting atop the three, clear symbolic composition, bronze and slate.",
  "three_pillars","三根柱子"),

 ("11","bureau","官僚与规则：看不见的实权","真正办事的人，权力藏得最深",
  ["还有一种权力，不在台前，藏在文件和公章后面——<span class='highlight'>官僚</span>。",
   "国王、总统换来换去，但真正管事的，常常是那群<span class='highlight'>办手续、盖公章、执行规则的人</span>。",
   "你想办个证、批个项目，快还是慢、批还是不批，往往他们一句话。他们官不大，<span class='highlight'>可实权不小</span>。",
   "这种权力的好处是专业、稳定；坏处是容易<span class='highlight'>踢皮球、效率低、没人负责</span>。看不见的权力，同样需要被监督。"],
  "官僚掌握'执行的实权'：不在台前却影响巨大。看不见的权力，更需要监督。",
  "A maze of government office counters and rubber stamps: ordinary citizens waiting in lines, faceless clerks behind windows stamping documents that decide fates, invisible but real power, stacks of paperwork, muted bureaucratic tones with a gold seal.",
  "rubber_stamp","公章"),

 ("12","ai2026","2026年：AI 开始替人做决定","算法，也是一种权力",
  ["到了今天，权力又多了一种你想不到的样子——<span class='highlight'>算法</span>。",
   "2026年，越来越多的事，不是人在做决定，而是AI：银行贷款批不批、简历先筛掉谁、你刷到什么视频、甚至路口红灯停几秒。",
   "这些决定影响着你我，可它是怎么算的，<span class='highlight'>没人告诉你，你也问不着</span>。",
   "这就提出了一个新问题：<span class='highlight'>当机器开始'说了算'，谁来管它？</span>它会不会偏心？犯了错找谁说理？这是你们这一代人，必须面对的新权力。"],
  "2026的新权力是算法：它替人做决定却不解释。如何约束AI，是你们这代人的新课题。",
  "Year 2026: a glowing AI brain or algorithm making decisions over tiny human lives, approving loans, filtering resumes, curating video feeds, traffic lights, humans looking up wondering who is in charge, no face behind the decisions, cool tech teal with warm human gold.",
  "ai_brain","AI大脑"),

 ("13","dot","写给点点：权力是责任","真正的好权力，是让人服，不是让人怕",
  ["点点，讲了一路权力，从拳头到选票再到AI，你可能觉得权力很吓人。",
   "其实权力本身没有好坏，<span class='highlight'>关键看它用来干什么、又被什么管着</span>。",
   "靠拳头和吓唬的权力，让人怕，但坐不长；靠故事和福利的权力，让人跟，但可能骗；只有<span class='highlight'>靠本事、讲道理、接受监督的权力，才让人真心服</span>。",
   "以后你也会有自己的'权力'：当班长、带团队、甚至只是影响身边的人。记住——",
   "<span class='highlight'>真正的权力，不是让多少人听你的，而是让多少人信你。权力越大，责任越大。</span>"],
  "全书落点：权力是用来担责任的，不是用来耍威风的。让人服的权力，才走得远。",
  "A child standing on a small hill at dawn, not on a throne but among peers, holding a small light (a lantern of responsibility) that others willingly gather around, a spiral of power history behind: spear, crown, charter, ballot, AI, all dissolving into stars, warm hopeful light.",
  "lantern_light","责任之灯"),
]
